#!/bin/bash
set -e
f=/app/pgdata/$1/postgresql.conf
shift
if [ -f $f ];  then
	port=$(grep "^port" $f | awk '{print $3}')

else
	echo "No such node: $f"
	exit 1
fi

if [ -z "$port" ]; then
	psql $@
fi
psql -p $port $@
