#!/bin/bash

start_pg() {
    d=$1
    echo "starting $d"
    pg_ctl -D $d -l $d/log start
}

export -f start_pg

find /app/pgdata -mindepth 1 -maxdepth 1 -type d | \
    parallel start_pg {}

echo "finished"
